enum NavigatorMap {
  App = 'App',
  Auth = 'Auth',
  AuthLoading = 'AuthLoading',
  Home = 'Home',
  FeelGoodTools = 'FeelGoodTools',
  Profile = 'Profile',
  SignIn = 'Sign In',
  SignUp = 'Sign Up',
  Welcome = 'Welcome',
  ForgotPassword = 'Forgot Password',
  HomeStack = 'HomeStack',
  GlobalScores = 'GlobalScores',
  Summary = 'Summary',
  Legend = 'Legend',
  Evaluate = 'Evaluate',
  Drafts = 'Drafts',
  ActionList = 'ActionList',
  AchievedActions = 'AchievedActions',
  ContactUS = 'Contact US',
  UserInfo = 'User Info',
  AccountSettings = 'Account Settings',
  Parameters = 'Parameters',
  DeleteAccount = 'Delete Account',
  FeelGoodToolsLegend = 'FeelGoodToolsLegend',
}

export default NavigatorMap;
